#lua

[[plugins]]
repo = 'andrejlevkovitch/vim-lua-format'
on_ft = ['lua']
lua_source = '''
    local api = vim.api

    api.nvim_create_autocmd(
        "BufWrite",{
            pattern = "*.lua",
            command = [[call LuaFormat()]],
        }
    )

'''
