[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo='previm/previm'
on_ft = ['markdown']
hook_add ='''
    set syntax=markdown
    autocmd BufRead,BufNewFile *.md set filetype=markdown
    nnoremap <silent> <C-p> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
    let g:previm_show_header=0
'''
