# ~/.config/nvim/dpp/toml/dpp.toml

# 【重要】dpp.vim の動作に必要なコアプラグインと拡張機能をすべて記述

[[plugins]]
repo = 'Shougo/dpp.vim'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'
on_source = 'dpp'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'
on_source = 'dpp'

[[plugins]]
repo = 'Shougo/dpp-ext-toml'
on_source = 'dpp'

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
on_source = 'dpp'

[[plugins]]
repo = 'Shougo/dpp-ext-local'
on_source = 'dpp'
